### ISSUE TITLE
How to Change values for Inline CSS?

### ISSUE THREAD

**Issue by prionkor** [bseth99/sandbox#1]
After applying the function I noticed its adding css inline styles to the container. 

``` html
<div class="ui-slider-wrapper ui-widget horizontal" style="font-size: 12px; width: 100px;">
    ....
</div>
```

Where does those inline css comes from? and how do i control/change them? I am now using `!important` for now.

**Comment by bseth99** [comment]
See the notes in the article: http://www.benknowscode.com/2013/01/adding-labelstick-marks-to-jquery-ui_4184.html

Basically, the font and sizing have to match the slider so the tick marks line up properly with the slider handle.  The widget controls these settings.
