### ISSUE TITLE
licensing conditions of your code

### ISSUE THREAD

**Issue by Locke** [bseth99/sandbox#2]
I just found some useful code here and on your blog. In order to use it in a project I'm working on I need to know your licensing conditions.

**Comment by bseth99** [comment]
I'm glad you found the code useful.  All the code is under the MIT license so you can use it as you like, however, a short acknowledgment is appreciated:

Copyright 2012-2013 Ben Olson, http://bseth99.github.io/
MIT license http://opensource.org/licenses/MIT
